### ISSUE TITLE
Add the ability to ignore validate and replaceSecrets Methods for test

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda/connector-sdk#112]
_What should we do_
Add the ability to create connector context with the ability to ignore validate and replaceSecrets Methods for the test.

_Why we do it_

I think it would be better if we extend the `contextBuilder` in the SDK to disable validation and secret replacement for such scenarios. It's a common use case, I think. So our test tool should support this. Can you create an issue for this? If you like, feel free to also propose how to support this in the `contextBuilder`.

_Originally posted by @tmetzke in https://github.com/camunda/connector-sendgrid/pull/100#discussion_r976848414_

**Comment by tmetzke** [comment]
Closing this as "Won't do", see also [PR comment](https://github.com/camunda/connector-sdk/pull/113#issuecomment-1257497815).
