### ISSUE TITLE
Allow to reuse the Feel Engine between Connector Job Handlers 

### ISSUE THREAD

**Issue by menski** [camunda/connector-sdk#121]
__Is your feature request related to a problem? Please describe.__

In the current approach each `ConnectorJobHandler` creates a new [`FeelEngineWrapper`](https://github.com/camunda/connector-sdk/blob/36b8106c6aead76936a00bd4f1be01e9bc44e17e/runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/api/outbound/ConnectorJobHandler.java#L60) which creates a [new FEEL engine](https://github.com/camunda/connector-sdk/blob/36b8106c6aead76936a00bd4f1be01e9bc44e17e/runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/impl/feel/FeelEngineWrapper.java#L40-L43) internally. This means for each connector registered in the runtime one FEEL engine is created. In our OOTB connector bundle for the getting started experience this corresponds to 6 FEEL engines. It is not needed that every connector has their own FEEL engine, and we could reduce the resources used by reusing the FEEL engine. 

__Describe the solution you'd like__

I want to be able to ensure that a single FEEL engine is created in my connector bundled runtime and shared by all connectors.

__Describe alternatives you've considered__

- Keep it as it is and create a new engine for each connector
- Add FEEL engine wrapper to public API signature to allow to inject a reused wrapper, disadvantage exposing of internal classes in a public API, see https://github.com/camunda/connector-sdk/pull/118
- Make FEEL engine wrapper a singleton to be used

__Additional context__

- [Reverted PR](https://github.com/camunda/connector-sdk/pull/118)
- [Slack Conversation](https://camunda.slack.com/archives/C0350959WG1/p1664222461893879)

**Comment by tmetzke** [comment]
I think one way here could be creating one public API class that allows handling Connector output (i.e. create variables and potentially also handle error expressions for BPMN Errors). It would provide public API like `createOutputVariables(Object responseContent, Map<String, String> jobHeaders)` and use the `FeelEngineWrapper` internally.

This public class would be created once in the `Main` and passed on to the `ConnectorJobHandler`. That way, we don't expose internal implementation details (the `FeelEngineWrapper`) into public API. But we also don't create a fixed singleton anywhere.
