### ISSUE TITLE
Accessing system variables in connector

### ISSUE THREAD

**Issue by vinothnivas** [camunda/connector-sdk#137]
While calling the end systems through connector, we need a provision to send the system variables like JobKey or ProcessInstanceId.

As part end system integration, especially for asynch communications where we send the indicators for the process instance like Job Key, Process Instance id, so the end system can use the zeebe client to complete the task and issue process instance level commands or track the process instances against the application business key.

It would be better if we have a way to pass the systems variables like place holders and the runtime can populate the system variables with actual values during the context initialization. In the FEEL expression we can mention like system.processintance.id or system.job.key.

We need a way to pass the system variables to end systems.

Alternate option:
From runtime, like fetchvariables to get the process instance variables, we can get the system variables as well. so it is accessible in the connector context

**Comment by nikku** [comment]
@vinothnivas Thanks for opening this issue. Could you update this issue to conform with our existing issue template?

Regarding your request on _system variable_ I do understand that you may want to pass around process instance ID. Any reason you don't just pass the business key around for correlation; it should be part of the process?

Why would you want to also pass around job worker key? If you could provide a concrete use-case (i.e. what valuable information you can extract from that?) that would be wonderful.

----

>  In the FEEL expression we can mention like system.processintance.id or system.job.key.

Could you sketch this out? Where would you assume both to be specified (referenced).

**Comment by jwulf** [comment]
If you use the "decoupled worker completion" pattern, you need to communicate the job key. This also relies on modifying the connector SPI / connector runtime to allow it to optionally *not* complete jobs.

For example: my connector sends the payload to a RabbitMQ queue. It gets pulled off that queue by some other process, transformed, then pushed onto a return queue. 

The return queue is serviced by another process that will now complete the job. The context of the connector invocation is gone. As it stands now, I must have completed the task (at the moment you cannot signal the connector runtime to *not* complete the job), so I will need to await an incoming message in my model, and my return queue processor will publish a message to the broker to move the process forward.

This will use message correlation, so it does not need the job key - it must use some process variable as a business key for correlation.

But: if we allow the connector to signal to the connector runtime to *not* complete the job, then my return queue processor can take the job key and complete the task using the CompleteJob API. 

This allows the model to be simpler, removing the incoming message event, which is a technical detail.

**Comment by berndruecker** [comment]
Two different things here:

1. We want to add internal Camunda information to a request. I totally see the point (even if we discourage users relying on internal ids). I think this should be generally possible in FEEL on Camunda 8 - not at all tied to connectors. 
2. Asynchronous completion of jobs. I know this is done with Job Workers regularly - but still this is not a pattern we support with connectors. Instead, you would have to do an outbound connector call and then wait for an inbound message next. In this case you will use some business data for message correlation.

Do we see a big urgency in this issue or could we simply wait for more pull from users?

**Comment by vinothnivas** [comment]
This is not an urgent request, as you have mentioned we can wait for more pull from users.

**Comment by MaxTru** [comment]
@vinothnivas to make it easier for other users to chime in on this request, can you please reformat the issue to comply with our issue templates? See [feature request](https://github.com/camunda/connector-sdk/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.md). Thank you

**Comment by MaxTru** [comment]
There is an issue in core zeebe already to make it possible to access system variables via FEEL. This would then also work in Connectors out-of-the-box. See https://github.com/camunda/zeebe/issues/10987.

Hence I am closing this issue here, let's use [the zeebe one](https://github.com/camunda/zeebe/issues/10987) for further discussions.

Please feel free to re-open if I missed something.
