### ISSUE TITLE
Refactor runtime-job-worker to use `spring-zeebe`

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#165]
__Is your feature request related to a problem? Please describe.__

A customized Zeebe Client Configuration like now

* Frustrates users, as it does not provide all configuration options (e.g. raised in https://github.com/camunda/connector-sdk/issues/65)
* Is a lot of additional work, as we have to duplicate efforts

__Describe the solution you'd like__

Instead of implementing its own `Main` method, the `runtime-job-worker` should leverage `spring-zeebe` to create workers.
See also https://github.com/camunda-community-hub/spring-zeebe#run-outboundconnectors.

__Describe alternatives you've considered__

I don't see other alternatives than manual coding in plain Java or using the existing spring Integration which is planned to be productized soon

__Further thoughts__

* If this project + https://github.com/camunda/connector-sdk-inbound-webhook + https://github.com/camunda/cloud-connector-bridge/ use the same mechanism to configure connections, it would allow to run them as one Java app somehow (e.g. for self-managed or maybe even for our own SaaS environment)

**Comment by tmetzke** [comment]
@berndruecker, would you mind adding what benefits this would bring in the `Is your feature request related to a problem? Please describe.` question, please?

**Comment by berndruecker** [comment]
Should support loading connectors via

* SPI
* Spring Beans

**Comment by berndruecker** [comment]
I will start a new runtime within the webhooks project for now (https://github.com/camunda/connector-sdk-inbound-webhook/issues/18#issuecomment-1290274855) and move it over as soon as possible.

**Comment by berndruecker** [comment]
I have a good basis to work on now here: https://github.com/camunda/connector-sdk/tree/joined-runtime. My next steps:

- [ ] Load SPI provided connectors and make available within Spring ecosystem
- [ ] Use connectors provided via Environment Variables within Spring ecosystem
- [ ] Map legacy environment variable to spring-zeebe ones --> *Not needed, as `applyOverrideEnvironmentVariables` defaults to true and thus environment variables will overwrite any Spring configured stuff anyway
- [ ] E2E Test Project

**Comment by berndruecker** [comment]
This is done with the PR merged. I open new PR's for other stuff...
