### ISSUE TITLE
Support Java 8 language level

### ISSUE THREAD

**Issue by tmetzke** [camunda/connector-sdk#168]
__Is your feature request related to a problem? Please describe.__

The Connector SDK `core` and Connector SDK `util` should be Java 8 compatible. This would allow the API and libary to be used in a Java 8 context.

This is relevant when adding the API to https://github.com/camunda-community-hub/spring-zeebe which officially still supports Java 8, so does our Java Client: https://docs.camunda.io/docs/reference/supported-environments/#clients.

I don't have a good feeling how many projects are still using Java 8. At the same time, if providing this compatibility is not a lot of pain, it is probably worth to keep this compatibility, as it generally makes it easier to use our clients. If there are very good reasons to go to a newer version - I would not see this a no-go (especially with Java 9 or Java 11). 

In the context of thisproject, I don't see a strong need for >Java 8, so I would love to keep Java 8 compatibility to not rigger a change in `spring-zeebe`.

_Does this enforce that Connector functions themselves are written with Java 8 language level as well so you can use them in Spring Zeebe?_

No, Connectors can be written in any Java version as long as the connector specifies what it needs. This would simply mean, that you need that Java version to run this connector.

I would further not make it a requirement for the runtimes in general. Java 8 compatibility would be just for the API and UTIL.

__Describe the solution you'd like__

See changes in https://github.com/camunda/connector-sdk/pull/171/files - that allows to build the while project with Java 8 without any change in functionality (and the code is not that ugly - so I would not consider that a show stopper)

__Describe alternatives you've considered__

If we go for Java 9 or Java 11, we would need to adjust the requirements for spring-zeebe to that version.

**Comment by berndruecker** [comment]
@tmetzke Updated the description

**Comment by menski** [comment]
> Before we do this, I'd like to get a comment from @menski here, regarding plans to ditch Java 8 for Zeebe Client. Camunda Platform 7 will actually move to Java 11 with 7.19, see https://github.com/camunda/camunda-bpm-platform/issues/2780.

@felix-mueller I would forward the question from Tobias to you, I'm not aware of plans to drop java 8, although I'm very in favor of it. Do you have any insides or plans regarding this?

**Comment by felix-mueller** [comment]
I was not aware of this (removing java 8 from C7). @toco-cam do we have any announcement planned already? I would love to get rid of Java 8 for C8 as well, but only if we dont have too much pushback from customers

**Comment by nikku** [comment]
As additional context Spring plans to drop Java 8 with their upcoming Spring@6 release, going to Java@17 as a baseline: https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6.

**Comment by toco-cam** [comment]
> 8 as well, but only if we dont have too much pushback from customers / users
@felix-mueller: For use Sping 6 and Spring Boot 3 is also the motivator. I will mention it today in the Webinar for the first time. We will send it out to the wider audience with the next [Alpha Release notification] (https://confluence.camunda.com/display/camBPM/Releases+-+Automation+Platform)

@berndruecker There is some data from [telemetry](https://ui.telemetry.camunda.cloud/goto/30ec1b8caee333ee51517e2ce190c7f6) which might not be super representative, therefore we choose to announce it early and wait for push-back.

**Comment by felix-mueller** [comment]
@toco-cam can we include Camunda 8 there as well?

**Comment by toco-cam** [comment]
> @toco-cam can we include Camunda 8 there as well?

Sure, as discussed.

**Comment by MaxTru** [comment]
Hi @berndruecker,
since you are assigned: is this still relevant? If so, can we move it to backlog? 
Are you actively working on this, or does it make sense to unassign you?
Is there any urgency on this topic?

**Comment by tmetzke** [comment]
@MaxTru, this is undecided, currently.
Technically, this should be possible. We would have to adjust some code in the SDK and the OOTB Connectors to adhere to Java language level 8 instead of 11.
This is therefore rather a product decision. Do we WANT to offer this compatibility or not? Should Connector development and execution be possible with Java 8 as well? Do we NEED this?

Assigning @bastiankoerber for a decision here and moving to the backlog.

**Comment by bastiankoerber** [comment]
@berndruecker for me it is hard to understand the user/customer impact. How often do we have this request? Is it common to support JDK 8  with a new software? Is it a roadblocker for any customer, that we don't support JDK8?

**Comment by toco-cam** [comment]
An update on our thoughts for C7. Java 8 will be the version that will stay with us till 2030 -https://www.oracle.com/java/technologies/java-se-support-roadmap.html. We are considering a dedicated LTS release of the Automation Platform to support customers using Java 8 so we can proceed with newer JDKs for components like Spring, ... . This is a first draft: https://docs.google.com/document/d/140YbX3Fr_Xq0K5oI51_zaqzUVVgL1QeSA3LeKX_u-Dw/edit#heading=h.tphvziwi0wim

**Comment by tmetzke** [comment]
> As the runtime moved to 17 (due to the spring boot dependency) are we ok to close this one @tmetzke ?

This is actually independent of the JDK version the runtime uses. This is about the language level of the SDK itself. It comes down to "What version do we require to run and build Connectors?".

This was a more significant concern when the Connector capabilities were still embedded into Spring Zeebe since that project has a minimum requirement of JDK 8. It created some friction since you had to use it with JDK 11+ when you wanted to run Connectors with it as well.

With the Connector runtime completely extracted (as far as I understand it), we can decide this separately for Connectors.

Not sure @berndruecker has any more concerns here now that the Connector runtime has been completely extracted from Spring Zeebe? It was his initial request to think about JDK 8 support in the Connector SDK.

**Comment by sbuettner** [comment]
As Java 17 is now the official baseline as of https://docs.camunda.io/docs/next/reference/supported-environments/ we can close this issue. Thanks for creating it though.

**Comment by tmetzke** [comment]
Happy to let this go 👍 One remark though: writing Connectors is mostly about writing specific [Camunda 8 Java clients](https://docs.camunda.io/docs/next/reference/supported-environments/#clients), which still are on JDK 8+.

**Comment by MaxTru** [comment]
Hi @sbuettner , can we please have an explicit follow-up to ensure Connectors are explicitly mentioned on https://docs.camunda.io/docs/next/reference/supported-environments/? Do you have an issue (or PR) already?

**Comment by sbuettner** [comment]
@MaxTru Yes, its tracked here: https://github.com/camunda/connectors-bundle/issues/668
