### ISSUE TITLE
Revert FeelEngineWrapper to use hardocded JavaValueMapper

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#178]
I vote to change the `FeelEngineWrapper` to use

```java
    feelEngine =
        new FeelEngine.Builder()
            .customValueMapper(new JavaValueMapper())
            .build();
```

as discussed in the recent PR: https://github.com/camunda/connector-sdk/pull/176

With the current version using SPI I have unpredictable behavior depending on which combination of libraries I pull in. 
I don't see any need to customize this at the moment - so I vote to avoid any possible problems down the road.

@tmetzke OK with you? Then I could create a PR for it.

**Comment by tmetzke** [comment]
Hi @berndruecker, this got drowned in my other notifications. 

I am generally fine with adjusting this for now.
However, could you try to reliably reproduce this issue so we can see where this is coming from?
I would love for us to understand why this can become an issue.

**Comment by berndruecker** [comment]
No worries - not urgent. I personally would hope to move all this wrapping to the feel-engine itself one day - so we don't have to think about it outside of it :-)
I haven't followed it so far - it is something with the SPI loading. Don't have enough time to understand the root of it - but will provide a PR for now 👍
