### ISSUE TITLE
Document connector structure / requirements

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#183]
__What should we do?__

We should properly describe what makes a connector and what requirements it need to follow, including directory structure.
As part of that, we also need to discuss those requirements :-) 

That might also lead into some thinking how community can distribute connectors down the line to find out, what's really important. 

__Why should we do it?__

See discussion in https://github.com/camunda-community-hub/camunda-8-connectors/pull/9#issuecomment-1289459910

**Comment by tmetzke** [comment]
One thing to start with is the [Connector template repository](https://github.com/camunda/connector-template). We link to that from the Community Hub repository, but a more prominent guide there would be better.

**Comment by berndruecker** [comment]
Duplicate of https://github.com/camunda/connector-sdk/issues/54
