### ISSUE TITLE
Add secret handling for inbound connectors

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#194]
See https://github.com/camunda/connector-sdk/pull/190#discussion_r1005825006:

Let me start with clarification, because secret is overloaded term and for the future reference for people in the future.

Secret here means a webhook token that concatenated with the content. It is defined when user creates a webhook. See GH example:

![grafik](https://user-images.githubusercontent.com/1217596/198107080-4bea75f9-33b8-41c3-91ed-7afbbdb99d5c.png)

The HMAC value is calculated as following:

HMAC_VALUE = hash(algo, content, secret). That will produce a salted hash value, e.g. sha256=aabbccdd. This values is passed together with a header, e.g. X-Hub-Signature-256.

Initially, it was implemented under impression that secret will be passed in header but not the hash value. The secret token has to be put by user manually in the field inbound.hmacSecret so that we recalculate the content hash and validate with one that arrived.
Member Author

So, yes, we don't plan to do anything in addition to validate webhook secret passcode, however, we need to add secrets.* handling logic so that user can store their secret in the Google Secrets Manager for SaaS or load them from the runtime / OS env - this logic is still pending. I am thinking, whether we can borrow it from the SDK.
Member

@berndruecker:

Understood . make sense! Yes - we should definitely align on the Google Secrets Manager logic - so reuse the SecretsHandler/SecretsProvider from the connector-core.
This way we can plug in different implementations (Google Secrets Manager for SaaS, Spring Environment for default runtime, probably custom Vault for self-managed, ...).

As I plan to merge the ConnectorBridge into the Runtime soon - this should be the same code for Inbound/Outbound then. Do you want to move this to another issue and take the lead? Or should I? Should probably not block merging this one.

**Comment by igpetrov** [comment]
Added to epic. @berndruecker if you haven't started it yet, I can take this one.

**Comment by berndruecker** [comment]
Nothing started - just that there might be some bigger changes on main coming up with https://github.com/camunda/connector-sdk/pull/188. If we are brave and can also release a 0.3.0-alpha1 tomorrow - I could probably push that to a state where we can merge it on main and take it from there. 

So happy it you look into it.

**Comment by berndruecker** [comment]
I think you should use the stuff from the SDK: https://github.com/camunda/connector-sdk/tree/main/core/src/main/java/io/camunda/connector/api/secret 

And e.g. in Spring I have an implementation simply going to the Spring Environment: https://github.com/camunda-community-hub/spring-zeebe/blob/master/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/jobhandling/SpringSecretProvider.java

And thus I would assume, that we somewhere have an implementation going against the Google Security Manager (code that must exist somewhere in the Cloud BRidge or Google Function runtime - have not yet fully looked into it)

**Comment by berndruecker** [comment]
I
