### ISSUE TITLE
Resolve release dependency chain `runtime` -> `spring-zeebe` -> `runtime-util`

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#195]
Currently we have a nasty cycle dependency, as spring-zeebe needs to depend on runtime-util, but the actual runtime needs spring-zeebe. This is a problem when releasing new features (as you might need to do a connector-sdk release, to enabne the spring-zeebe release which is needed to move forward in cnnectors.

However, I don't think we should change that now - as it is also pretty convenient to have everything in one build, especially for extending the SDK towards Inbound (e.g. Subscription & Polling).

But at some point in time I think we should split the current connector-sdk into:

- `connector-sdk`, containing the real SDK (`core`) and Utilities ('runtime-util') (no Spring dependency here)
- `connector-runtime` containing the runtime (spring-zeebe based stuff)

**Comment by tmetzke** [comment]
Just to understand this:

We don't technically have a cyclic dependency issue here, right? That would mean, as far as I know, that `runtime` depends on `spring-zeebe` and `spring-zeebe` depends on `runtime`. 

This is rather a release issue, right? I agree with the proposal that we might need to extract the runtime from the SDK.

Then again, I was just wondering: 

* Can't Spring Zeebe simply BE the runtime?
* Do we actually need another `runtime` project at all?
* What benefit does it provide?
* Can we integrate the stuff that is needed into Spring Zeebe itself?

**Comment by berndruecker** [comment]
I like the idea of Spring Boot being the runtime. 

We could basically move the current `runtime` to `spring-zeebe-connector-runtime` as submodule in spring Zeebe. The code from `inbound` might be distributed to either runtime-util or this new module. Some generic stuff might also end up in spring-zeebe itself - not yet sure. 

Connector-SDK would "only" be:

- connector-core
- connector-validation
- runtime-util 

This way, connector developer would look towards https://github.com/camunda/connector-sdk and runtime folks towards https://github.com/camunda-community-hub/spring-zeebe + `/connector-runtime`?

Would https://github.com/camunda/connectors-bundle stay an independant repo?

**Comment by tmetzke** [comment]
That sounds a lot like my vision for this, yes 👍 
The SDK itself would just bring along the basic components to build Connectors (exactly as you detailed it).
Spring Zeebe would be the default runtime that we deliver.

Connectors Bundle delivers a whole "distribution" including element templates and backend (runtime + Camunda-provided Connectors). If we want something like this inside Spring Zeebe, let's add it. 
But I think it can stay separate for now.

**Comment by berndruecker** [comment]
I like that direction. I would prioritize https://github.com/camunda/connector-sdk/issues/235 higher for now - but would be happy to drive it afterwards.

**Comment by berndruecker** [comment]
Howdy @tmetzke. I might start this now because when looking into SecretProviders I recognized that the `ConnectorJobHandler` is no longer used (but the Spring logic to execute functions) - and thus also the nice BpmnError logic is actually not triggered in the new runtime. I will make sure this comes back there - but also delete the unused class in util to avoid such potential problems in the future. To make this nice - I would pobably go ahead and move some other util classes over to spring-zeebe right now as it makes things much easier...

**Comment by tmetzke** [comment]
Let's maybe have a look together at why you cannot use the `ConnectorJobHandler`. That might be the more worthwhile approach, I think. Happy to jump on a call.

**Comment by tmetzke** [comment]
I made a proposal with https://github.com/camunda-community-hub/spring-zeebe/pull/253. Let's discuss this whenever you have time.

**Comment by tmetzke** [comment]
> I made a proposal with [camunda-community-hub/spring-zeebe#253](https://github.com/camunda-community-hub/spring-zeebe/pull/253). Let's discuss this whenever you have time.

I made a proposal with https://github.com/camunda-community-hub/spring-zeebe/pull/253. Let's discuss this whenever you have time.

**Comment by berndruecker** [comment]
I started a PR (https://github.com/camunda/connectors-bundle/pull/19) but would now wait for the next SDK alpha being released and release Spring Zeebe 8.1.3 based on this - and when this is available on Maven Central I can check that the Docker file creation is working.

**Comment by tmetzke** [comment]
All done
