### ISSUE TITLE
Prototype Subscription Inbound Connector with RabbitMQ

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#198]
- Extend https://github.com/camunda/connector-rabbitmq with an Inbound Subscription Connector
- Add SubscriptionInboundConnector to SDK
- Discuss if Inbound/Outbound should be within one repo (I think: yes)
- Add Test

After Subscription has landed, we can do Polling next an open an issue for that (first thoughts were here: https://github.com/camunda/connector-sdk-inbound-webhook/issues/8)

**Comment by berndruecker** [comment]
First thoughts here: https://github.com/camunda/connector-sdk-inbound-webhook/issues/4#issuecomment-1282759410

**Comment by igpetrov** [comment]
Hi @berndruecker,

Do you mind if I take this one a make a basic prototype?

**Comment by berndruecker** [comment]
Happy to (if you have spare time - sounded like there is non from Mo - but happy to be mistaken). 

I have a working RabbitMQ prototype somewhere, if it is helpful I can dig it out. It lead to those proposals back in the days: https://github.com/camunda/connector-sdk-inbound-webhook/blob/more-connector-types/src/main/java/io/camunda/connector/inbound/sdk/ideas/SubscriptionInboundConnector.java

**Comment by berndruecker** [comment]
I started doing a quick first stab at RabbitMQ. My message already started a process instance :-)

The current stab consists out of three draft PRs:

1. Additions to the Connector SDK: https://github.com/camunda/connector-sdk/pull/334
2. Spring Zeebe changes: https://github.com/camunda-community-hub/spring-zeebe/pull/311
3. RabbitMQ example using the stuff: https://github.com/camunda/connectors-bundle/pull/191

@chillleader: Let me know when you want to start implementing, happy to give you a walkthrough
