### ISSUE TITLE
Adjust Connector Runtime docs & release notes for 0.3.0

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#203]
There will be slight modifications with the new Spring-based runtime. 
We need to update the docs accordingly and add release notes.

Tech docs:

- [x] Adjust https://docs.camunda.io/docs/self-managed/platform-deployment/manual/#run-connectors (should comply with what we have in `connector-runtime#readme`). - https://github.com/camunda/camunda-platform-docs/pull/1499
- [x] Adjust validation imports at https://docs.camunda.io/docs/next/components/connectors/custom-built-connectors/connector-sdk/#validation - https://github.com/camunda/camunda-platform-docs/pull/1499
- [x] Document important/breaking changes (https://github.com/camunda/camunda-platform-docs/pull/1456):
  * All Connectors: rename imports `jakarta.validation` to `javax.validation` 
  * Module `connector-runtime-job-worker` moved to Spring Zeebe's `connector-runtime`
  * Running the runtime will change to
```bash
java -cp spring-zeebe-connector-runtime-VERSION-with-dependencies.jar:connector-http-json-VERSION-with-dependencies.jar io.camunda.connector.runtime.ConnectorRuntimeApplication
```

**Comment by tmetzke** [comment]
You can add migration hints to https://github.com/camunda/camunda-platform-docs/pull/1456
