### ISSUE TITLE
Document classloading with multiple connectors in one runtime

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#205]
See https://github.com/camunda/team-connectors/issues/125

Classloading problems already happened with `jackson`, but the more connectors we build, the more classloading issues we will see.

**Ideas**

- **Relocate** library classes via mvn shade plugin in connector fat jars
  - Could be configured by an obligatory parent pom
  - Maybe simply relocate all classes except connector API to make sure, we don't have overlaps
  - Con:
    - Every connector brings a copy of common libraries
    - package names (e.g. in exceptions) are "unnormal"
    - Connector developers need to stick to the rules
- **Align** the library versions for all connectors (at least for common libraries)
  - For example via parent pom or BOM
  - Con: 
    - Hard to update versions (would need a rebuild of all connectors to use the latest version)
    - Hard to control that connector developers really stick to it
- Don't build a jar with dependencies per connector but a single jar with dependencies bundled with all connectors (**Maven** does dependency conflict resolution)
  - Easy to do for our own OOTB bundle of connectors
  - Con:
     - Does not allow for a "DevOps"-way of using connectors (e.g. just stitch together a couple of jars in a Docker file
- Some Docker magic to do a mvn build on-the-fly
  -  We could provide a Docker file that can create a big Maven build with all provided connectors to produce its own uber JAR on-the-fly (I think)
  - Con:
     - Tied to docker
     - Could get us into some nasty trouble ;-)
- Build some **custom classloading** isolation 
  - Con:
    - Super complex
    - App servers and OSGI did always struggle with that
- Add some **remote invocation** to the connector code (like via Connector Bridge at the moment, or even RMI) to put connector into own JVM
  - Isolates connectors from the runtime much better, probably helpful also in other regards (thinking about running community connectors in a sandbox)
  - Con:
    - Added complexity in deployment
    - Less efficiency and more possible failure cases to handle

**Comment by berndruecker** [comment]
Thoughts on **Fat Jar** vs **Maven Build** from @tmetzke:

Yes, building this with Maven is one way of working around this and we have considered this. We think this doesn't solve the issue for more DevOps-ish people that want to run/administer Connectors. They'd rather want to decide which Connectors to add to the runtime without handling Maven dependencies, but rather adding them to Docker images or k8s clusters. That's why we currently have the FAT JARs approach. So administrators can mix and match a pre-packaged runtime (that we provide as a Docker image) with any Connectors they'd like to run.

Maybe there is a way that a) isolates the components in a better way while still making them callable from the runtime and b) is also easily applicable for other Connector developers so they can distribute their custom Connectors as well. Providing a FAT JAR for their Connectors is rather simple in general (we can bake this into the Connector template repository and they release that to Maven Central or GitHub releases).

We could also say "Here is a POM file that contains the runtime and our Connectors as dependencies, nicely packing everything together as a Docker image using jib-maven-plugin. Use this as a blueprint and add/remove all the Connectors you need, run mvn clean package and you're good". But we believe this might not cater to how those personas usually operate.
Does that make sense? Thoughts?

**Comment by berndruecker** [comment]
I will look into this again after my vacation. I totally see the approach of the DevOps approach, especially for custom-build connectors (at the same time the priority might be the "connector-bundle" - which we could also provide via docker and just ship all connectors - no harm).
https://camunda.slack.com/archives/C0350959WG1/p1666866943719769

**Comment by berndruecker** [comment]
Spontaneously I like the Maven Shade Relocate approach. Looking into this right now. 
@tmetzke FYI, I currently have some issues with the Spring-based runtime picking up connectors via fat jar. I am on it.

**Comment by tmetzke** [comment]
Thanks for the update, @berndruecker. We use the relocation approach as well for some Connectors, e.g. [SQS](https://github.com/camunda/connector-sqs/blob/main/pom.xml).

**Comment by tmetzke** [comment]
Also mentioned in the tech docs: https://docs.camunda.io/docs/self-managed/platform-deployment/docker/#custom-set-of-connectors

**Comment by berndruecker** [comment]
I quickly looked into maven shade relocate a bit and also tried another approach: Try to shade as much as possible to prevent potential upcoming classloading issues. Unfortunately that might lead to some other wired problems (e.g. moving some META-INF files) and it thus feels not good. Also, all packages change, which might make problems hard to spot/google. For example something wired around SSLContext loading (haven't fully investigated - I find this just the tip of the iceberg): 
```log
java.security.NoSuchAlgorithmException: httpjson.TLS SSLContext not available
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:185)
        at httpjson.org.apache.http.ssl.SSLContexts.createDefault(SSLContexts.java:51)
```

So I would propose the following:

1. Keep mvn shade relocate as a recommendation for libraries where we know/learn that people can get in trouble. This might come up regularly and we can only solve it after seeing it. At the same time, it is hopefully not super common and thus might not be too big of a problem.

2. We do a Maven project for our own connector bundle. While this comes with the downside, that we might not experience the problems of (1) first-hand, I think it gives us a much more stable and predictable solution for running a bunch of connectors easily. This bundle can be used in SaaS, but also as get-started for self-managed. Only if users want to customize the connector set (or add own ones), they use the `java -cp` approach to add fat jars.

3. If (1) turns out to be more problematic than expected, we could work on a layered Docker build to do a MVN build on the fly (e.g. a Docker file that adjusts the pom.xml to add connector dependencies, does a build, and use the resulting JAR as executable). 

The command for the connector-runtime changes to the following with Spring Boot:

```bash
java -Dloader.path=connector-http-json-0.11.0-SNAPSHOT-with-dependencies.jar -jar connector-runtime-0.3.0-SNAPSHOT.jar
```
See https://github.com/camunda/connector-sdk/pull/215

**Comment by berndruecker** [comment]
Just for the record, Kafka Connect seems to dance around the problem the same way: https://stackoverflow.com/questions/54888135/jersey-wadlautodiscoverable-cast-error-due-to-apparent-classpath-conflict

**Comment by tmetzke** [comment]
Yeah, everybody does the "dance" somehow in Java. Java Enterprise servers of all kinds have been doing the dance for decades 😄

**Comment by tmetzke** [comment]
> The command for the connector-runtime changes to the following with Spring Boot:
> 
> ```shell
> java -Dloader.path=connector-http-json-0.11.0-SNAPSHOT-with-dependencies.jar -jar connector-runtime-0.3.0-SNAPSHOT.jar
> ```

Can we add this to the list of breaking things to document? We need to adjust the camunda.docs.io for that.

**Comment by berndruecker** [comment]
Have it on the radar for a 0.3.0 release. Let's wait for it to finally settle (will continue after my holidays next week)

**Comment by tmetzke** [comment]
For reference: https://github.com/camunda/connector-sdk/issues/203 tracks necessary changes

**Comment by berndruecker** [comment]
We settled on Maven Shade for the runtime (despite using Spring Boot), so the commands do not change.

However, I think it is worth to document classloading thoughts in the runtime readme. I will use this issue for it.

**Comment by tmetzke** [comment]
> However, I think it is worth to document classloading thoughts in the runtime readme. I will use this issue for it.

I agree 👍
There is something in the README already: https://github.com/camunda/connector-sdk/tree/main/runtime#via-docker
But it might not be enough.

**Comment by berndruecker** [comment]
Added https://github.com/camunda-community-hub/spring-zeebe/commit/b9d08175b2c890b9d820748e8aa6c3a5e7ec48b7 - closing this issue now
