### ISSUE TITLE
Double check logback dependency (EPL 1.0 or LGPL) with legal

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#206]
See https://github.com/camunda/connector-sdk/pull/204#issuecomment-1293522310 and https://jira.camunda.com/browse/OSS-5

When clarified adjust used licenses.

If in doubt exclude logback and use log4j

**Comment by tmetzke** [comment]
This is used by Optimize as well: https://docs.camunda.io/docs/reference/dependencies/#optimize-dependencies-back-end

**Comment by berndruecker** [comment]
Legal gave a thumbs up - so it is not a problem.
"Are we linking dynamically (as opposed to statically): If yes, good.
Are we NOT modifying (e.g., making a derivative) the code? If yes, good."

If we somehow experience any acceptance problems with EPL we could still exclude backlog and hook in slf4j instead.
