### ISSUE TITLE
ZeebeSpringTest issue: class file has wrong version 61.0, should be 55.0

### ISSUE THREAD

**Issue by Fadelbayabi** [camunda/connector-sdk#220]
__Describe the Bug__

connector-inbound failure. 
 error: 
```
 cannot access io.camunda.zeebe.spring.test.ZeebeSpringTest
[ERROR]   bad class file: ..\.m2\repository\io\camunda\spring-zeebe-test\8.1.2\spring-zeebe-test-8.1.2.jar(/io/camunda/zeebe/spring/test/ZeebeSpringTest.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] /../connector-sdk/inbound/src/test/java/io/camunda/connector/inbound/WebhookControllerTestZeebeTests.java:[46,2] cannot find symbol
[ERROR]   symbol: class ZeebeSpringTest
```

__Steps to Reproduce__

1. run : mvn clean package

__Expected Behavior__

should build successfully. 

__Environment__

- OS: [ Windows 11]

**Comment by berndruecker** [comment]
Hi @Fadelbayabi - the tests use Java 17 to use a complete Java in memory engine (see https://github.com/camunda-community-hub/spring-zeebe/#writing-test-cases). There is no plan to change this, as the built artifacts are not affected and can still run with an older Java version. 

Please use Java >=17  for a build.
