### ISSUE TITLE
Get `inbound` ready for `0.3.0`

### ISSUE THREAD

**Issue by tmetzke** [camunda/connector-sdk#228]
__What should we do?__

Overall, we need to ensure `inbound` (although still a work in progress) is coherent and can be used (we can also list limitations, if necessary). Plus, `inbound` should not introduce any regressions/unexpected behavior for `outbound` users by default (e.g. creating a webhook endpoint, spin up Operate importers and poll).

- [x] Validate `inbound` README (currently, the described procedures don't work from inside the module or are unclear where to be run from)
- [x] Ensure including `inbound` in `runtime` does not spin up resources by default (webhook endpoint, Operate polling, ...) --> https://github.com/camunda/connector-sdk/issues/232
- [x] Remove Spring Zeebe from `inbound` (should not be necessary), it's provided by `runtime`.

__Why should we do it?__

Get `inbound` release-ready for `0.3.0`.

**Comment by tmetzke** [comment]
## Reasoning

As far as I can see, we want to have the following in the long run:
- Runtime contains Spring Zeebe
- Runtime has a main Spring Boot class
- Runtime includes outbound (via Spring Zeebe) and inbound (via inbound) capabilities
- You can configure what to start externally (outbound connector functions, inbound connector webhook endpoint, ...)

But I think we're not there yet. Too much stuff simply starts by default. It might make sense to give ourselves more time to get this right. Thus, we could currently keep `runtime` as the Outbound runtime and keep `inbound` self-contained and separate from `runtime` until we're ready (e.g. `0.4.0`).

**Comment by berndruecker** [comment]
Working on it in PR https://github.com/camunda/connector-sdk/pull/231 (draft)

**Comment by berndruecker** [comment]
Would you agree this can be closed @tmetzke? 
Also related to https://github.com/camunda/connector-sdk/issues/202 which is "close to be closed" (waiting for some PR's to be merged) :-)
