### ISSUE TITLE
Allow secrets in any position of a string

### ISSUE THREAD

**Issue by wollefitz** [camunda/connector-sdk#236]
__Define the problem__

As a user, I want to be able to concatenate a secret with another string to be able to access REST APIs that offer a custom authentication format (e.g. the GitHub API that expects `token <TOKEN>` as a value of the `Authorization` header, see for example https://docs.github.com/en/rest/issues/issues#create-an-issue).

This doesn't work with the current implementation because secrets are only replaced if a string only contains a secret and nothing else:

https://github.com/camunda/cloud-connector-http-json/blob/9950be85911e0ad70bc4fd29d51df54561956a87/src/main/java/io/camunda/connector/http/SecretStore.java#L21

__Describe the solution__

* Allow secrets in any position of a string and not just replace it if the string only contains the secret and nothing else. 
* Document the current limitation in the meantime as users might not be aware of it

**Comment by tmetzke** [comment]
Transferred this to the SDK since this is needed for all Connectors.

**Comment by tmetzke** [comment]
Discussion around this also came up in Slack: https://camunda.slack.com/archives/C01QYD808A3/p1667818834458649?thread_ts=1667808487.864399&cid=C01QYD808A3

The gist:

* Allow mustache-style templating in Connector inputs (passed on by Zeebe, not interpreted there).
* Users can write something like "Authorization: Bearer {{secrets.TOKEN}}", where `{{secrets.TOKEN}}` will be replaced with a known secret.
* For convenience and backward-compatibility, we could keep to allow whole-content secrets as well, i.e. inputs like "secrets.TOKEN".
