### ISSUE TITLE
Allow access to headers

### ISSUE THREAD

**Issue by jwulf** [camunda/connector-sdk#247]
__Is your feature request related to a problem? Please describe.__

Not sure if I'm missing something, but it looks like there is no way to get access to headers in a connector?

__Describe the solution you'd like__

Maybe a `getHeaders` method, similar to `getVariablesAsType`, to allow access to task headers.

__Describe alternatives you've considered__

Don't use headers, only variables.

**Comment by nikku** [comment]
Could you elaborate where you'd need headers? 

Headers have the disadvantage to be static only and in most usage scenarios that is not desired. Inputs on the other hand can be static values `hello` or expressions `= foobar + "!"`, improving the expressiveness of templates.

**Comment by jwulf** [comment]
Do the variables from the connector template get merged into the payload past the connector? 

Headers are scoped to the task, so you don't have to worry about namespacing and collisions/overwriting.

**Comment by nikku** [comment]
> Headers are scoped to the task, so you don't have to worry about namespacing and collisions/overwriting.

That is an upside. The idea is that variable merging is prevented through namespacing, however we've already received indications that our existing implementation is prone to unintended "clashes".

**Comment by MaxTru** [comment]
Given that headers have the clear scoping this is a valid use-case. Moving it to backlog.

**Comment by igpetrov** [comment]
Taking a look

**Comment by igpetrov** [comment]
Added headers, and JSON representation of complete activated job for those who need more flexibility.

https://github.com/camunda/connector-sdk/pull/446
