### ISSUE TITLE
Add `LocalContainerRuntime` to test scope for connector template

### ISSUE THREAD

**Issue by berndruecker** [camunda/connector-sdk#271]
See https://github.com/camunda/connector-http-json/pull/177#discussion_r1029383992

Add docs how to run connectors in your IDE with that.

**Comment by tmetzke** [comment]
@chillleader, let's discuss this as a next topic when you're done with your current tasks.

**Comment by berndruecker** [comment]
For reference: https://github.com/camunda/connector-sdk/issues/72 also mentioned this topic originally, would be great to probably also add some docs

**Comment by igpetrov** [comment]
Hi @chillleader,

Is this ticket completed or do you expect more changes?

**Comment by chillleader** [comment]
Connector templates were updated.
Propagating these changes to each connector seems unreasonable due to ongoing transition to mono repo, so I'm closing this issue.
