### ISSUE TITLE
Class cast exception on AbstractOutboundConnectorContext  0.3.0

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda/connector-sdk#274]
__Describe the Bug__

When a job is ready for the connector, it goes here
`io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler
` line 45:
```

try {
  Object result = this.call.execute(new ConnectorJobHandler.JobHandlerContext(job));
  client.newCompleteCommand(job).variables(this.createOutputVariables(result, job.getCustomHeaders())).send().join();
  LOGGER.debug("Completed job {}", job.getKey());
} catch (Exception var4) {
  LOGGER.error("Failed to process job {}", job.getKey(), var4);
  client.newFailCommand(job).retries(0).errorMessage(var4.getMessage()).send().join();
}
```

And thanks to “Force Step Into” of Intellij, I detect that the missing class is the one:
`io.camunda.connector.impl.outbound.AbstractOutboundConnectorContext
`

Note: it is strange that the catch on line 48 does not catch this exception, nor the catch(Exception) ion JobRunnableFactory::35 – so I don’t see anything in the console except
2022-11-22 11:41:03.711  INFO 17880 --- [pool-2-thread-1] i.c.c.r.j.a.o.ConnectorJobHandler        : Received job 2251799813712369

__Steps to Reproduce__

1. Download the CherryFramework
2. Move to the branch "io_camunda_connector"
3. verify that the version is 0.3.0
        <connector-core.version>0.3.0</connector-core.version>
4. under src/test/resources/connectorworker open the BPMN process PingConnectorWorker. Upload it on a Zeebe server (use a local Zeebe) and start a process instance
5. Check src/main/resources/application.properties. By default, it used your local Zeebe server. (you can change the properties to point to your Zeebe Engine in the cloud)

6.  on your Intellij, start io.camunda.CherryApplication

You will face the issue.

__Expected Behavior__

It should work as 0.2.0, calling the connector 

__Environment__

- OS:  Windows 11]
- Library version: [0.3.0]
- Camunda version: [8.1.0(self-managed)]

**Comment by pierre-yves-monnet** [comment]
Additional information:
The Cherry Framework creates workers on `CherryJobRunnerFactory` by this method:
```

import io.camunda.connector.runtime.jobworker.api.outbound.ConnectorJobHandler;

               JobWorkerBuilderStep1.JobWorkerBuilderStep3 jobWorkerBuild = createJobWorker(running.runner);
                running.containerJobWorker.jobWorker = jobWorkerBuild.open();

```
and
```

  private JobWorkerBuilderStep1.JobWorkerBuilderStep3 createJobWorker(AbstractRunner runner) throws OperationException {
        JobWorkerBuilderStep1.JobWorkerBuilderStep2 jobWorkerBuild2 = zeebeContainer.getZeebeClient().newWorker()
                .jobType(runner.getType());

        JobWorkerBuilderStep1.JobWorkerBuilderStep3 jobWorkerBuild3;
....
            jobWorkerBuild3 = jobWorkerBuild2.handler(new ConnectorJobHandler(abstractConnector));
 .....
        jobWorkerBuild3.name(runner.getName() == null ? runner.getType() : runner.getName());
...
        return jobWorkerBuild3;
    }
```

**Comment by pierre-yves-monnet** [comment]
Thanks for the Update guide.
One improvement, maybe?
The guide says
`The runtime-util artifact replaces the runtime-job-worker artifact.
`
Does it seem this is only information? 
Because I tried to replace
```
   <dependency>
           <groupId>io.camunda.connector</groupId>
           <artifactId>connector-runtime-job-worker</artifactId>
           <version>0.2.2</version>
       </dependency>
```
by
```
 <dependency>
            <groupId>io.camunda.connector</groupId>
            <artifactId>connector-runtime-util</artifactId>
            <version>8.1.3</version>
        </dependency>
```

But I got a io.camunda.connector:connector-runtime-util:jar:8.1.3 was not found (but it is here https://repo1.maven.org/maven2/io/camunda/spring-zeebe-connector-runtime/8.1.3/ but the artifactId is not this in the pom.xml)

So, to try, I removed this dependency and... everything runs fine!

**Comment by tmetzke** [comment]
Hey @pierre-yves-monnet,

the previous `runtime-job-worker` artifact covered two things at the same time: 
- A job hander for Connectors, i.e. `ConnectorJobHandler`. You use this to build your own Connector Runtime application.
- An application to run Connectors using ENV variables. You use this to run Connectors.

This is now separated:
- The `connector-runtime-util` provides the job handler for Connectors. It is versioned with the SDK, so it has version `0.3.0`.
- The `spring-zeebe-connector-runtime` provides an application to run Connectors. It is versioned with Spring Zeebe, the latest stable version is `8.1.6`.

It depends on what you want to achieve. Want to build your own Connector Runtime? Use the `connector-runtime-util`. Want to simply run Connectors? Use Spring Zeebe's Connector Runtime. The Spring Zeebe artifact brings along the `connector-runtime-util` as well, since it uses this to build the Runtime, of course.
