### ISSUE TITLE
Make outbound aspect more explicit

### ISSUE THREAD

**Issue by nikku** [camunda/connector-sdk#29]
__What should we do?__

* Move outbound connector API to the `outbound.api` package
* Rename `ConnectorFunction` to `OutboundConnectorFunction`
* Clearly document the _outbound_ bits as part of the SDK

__Why should we do it?__

To prevent future migration we can already prepare for inbound to join the SDK.

**Comment by nikku** [comment]
Moving to `backlog` for now and follow up once we cleared inbound.

**Comment by PreetiNirwal** [comment]
Referencing the document that suggests this update, pls see [here](https://docs.google.com/document/d/1momVaeFoJELUHQMRZ3vgPGdVtnsVWntivSrM60t1NL8/edit#).
