### ISSUE TITLE
Make `ConnectorConfigurationUtil` API

### ISSUE THREAD

**Issue by tmetzke** [camunda/connector-sdk#295]
__What should we do?__

- [ ] Make `ConnectorConfigurationUtil` accessible as API (currently, it is a class in an `impl` package). Potentially also rename the class to something more focused on environment variables. We could also rework how this is wired (e.g. in the Connector `context` rather than statically, but this might not work in all use cases so static access might still make the most sense).
- [ ] Document how a Connector can fetch environment variables (at least in the [Connector SDK documentation](https://docs.camunda.io/docs/components/connectors/custom-built-connectors/connector-sdk/)).
- [ ] Document how a Connector runtime can set the `ConnectorPropertyResolver` (either in the Connector SDK documentation or the `runtime-util` module's README in the SDK).

__Why should we do it?__

- The `ConnectorConfigurationUtil` can/should be used in Connectors to resolve environment properties. See [REST Connector](https://github.com/camunda/connector-http-json/blob/281e07732d1a7916e0c6e104df774ddba1491328/src/main/java/io/camunda/connector/http/HttpJsonFunction.java#L84) for an example.
- The Connector runtimes will set the environment properties resolver as they see fit (e.g. [Spring Zeebe](https://github.com/camunda-community-hub/spring-zeebe/blob/master/client/spring-zeebe/src/main/java/io/camunda/zeebe/spring/client/connector/ConnectorConfiguration.java#L35) using Spring Environment variables rather than `System#env`).

**Comment by tmetzke** [comment]
@chillleader or @markfarkas-camunda, maybe you have time to tackle this soon. Not a top priority for the `0.4.0` release, but would be nice to align this beforehand.

**Comment by bastiankoerber** [comment]
we decided, that we don't need it, since we do the Spring integration. If you have follow up question, feel free to reach out to @chillleader
