### ISSUE TITLE
Allow more than one SecretProvider

### ISSUE THREAD

**Issue by bulivlad** [camunda/connector-sdk#425]
__Is your feature request related to a problem? Please describe.__

We're looking to use as many out of the box connectors as we can and also trying to hard code as less configurations in the flow as it will make it hard to change configurations in the future.

We are currently need to get properties from other different sources/files so we would need use multiple secrets providers.

__Describe the solution you'd like__

The `SecretHandler` object should have a `List<SecretProvider>` instead of single `SecretProvider` and check with every provider in the list when it getting the secrets.

__Describe alternatives you've considered__

Creating a custom secret provider and use it to call different other secret providers in order to retrieve the secrets from different sources

**Comment by chillleader** [comment]
That makes sense - I'm moving this to our backlog.

Do you have any thoughts on how the secret managers should be sorted? It seems reasonable to have a possibility to configure the order in the connector runtime's properties, e.g.:
```
camunda:
  connector:
    secret-providers:
      - aws
      - gcp
      - default
```
The runtime would then attempt to find the secret in `aws` first, then in `gcp`, and then fall back to the default one.

The runtime could fall back to arbitrary lookup order if no ordering config was provided.

**Comment by bulivlad** [comment]
This kind of configuration looks fair
```
camunda:
  connector:
    secret-providers:
      - aws
      - gcp
      - default
```
Maybe discovering them using SPI and sorting them through the properties file
I would not include the `default` one in the configuration but maybe having it by default configured to avoid errors where no provider is configured

**Comment by chillleader** [comment]
## Development update

We decided to introduce a new `SecretProviderAggregator` interface. It is an extension of the `SecretProvider` base interface and it implements a strategy of working with multiple providers.

We decided not to implement the properties-based strategy discussed above as part of our SDK/Runtime. The default strategy that we are going to provide will return the secret value from the first secret provider that is able to return one, in a non-deterministic order.

For use cases where another strategy is required, users will be able to implement `SecretProviderAggregator` on their side where this custom strategy is implemented. In a custom implementation, it is possible to work with configuration properties or anything else. The Spring Zeebe Connector Runtime will be able to consume custom `SecretProviderAggregator` implementations from the Spring context.
