### ISSUE TITLE
Allow alpha/rc releases

### ISSUE THREAD

**Issue by tmetzke** [camunda/connector-sdk#58]
__What should we do?__

Allow to build alpha and/or release candidate releases of the SDK.

- [ ] Adjust [release action](https://github.com/camunda/connector-sdk/actions/workflows/RELEASE.yml) to consider qualifiers.

__Why should we do it?__

Currently, as described in the [README](https://github.com/camunda/connector-sdk#build-a-release), building those qualified releases is not really conveniently supported. As soon as we reach version `1.x`, we should be able to create such releases for stability and consistency reasons.

**Comment by PreetiNirwal** [comment]
Hi @tmetzke, I'm not sure if this should get added to our ticket here or not, what are your thoughts?
https://github.com/camunda/cloud-connectors/issues/97

**Comment by tmetzke** [comment]
I think it's not necessary, short term. We can still build this after 1.0, for example. Sooner is always better, but I think it's not a blocker for 1.0 for example.
