### ISSUE TITLE
Use ZeebeClientFactory in Connector Runtime Main

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/connector-sdk#65]
__Is your feature request related to a problem? Please describe.__

Atm, the Connector SDK runtime Main seems to only serve local plaintext OR Camunda Cloud. As I tried to test with a staging environment, the runtime Main could not be used. Instead, I had to bootstrap the client in another Main class. This will also be the case with self-managed C8 clusters.

__Describe the solution you'd like__

I want the default Bootstrapping mechanism to be able to pick up a custom ZeebeClientFactory and use it.

__Describe alternatives you've considered__

An alternative would be to use env variables and map them. But I think it would be handsome to empower Connector developers in a way that a self-made ZeebeClientFactory can be used to get started in a C8 SM quickly.

__Additional context__

I know this is currently not really in scope. Anyway, this is a low-hanging fruit from my perspective.

**Comment by nikku** [comment]
Could you provide an example that shows how custom ZeebeClientFactory is desired? Do you take inspiration from existing job worker capabilities here? If so, please link such supporting docs.

**Comment by nikku** [comment]
As you suggested in the alternatives: Currently configuration happens via environment variables and that is also the recommended way to configure systems [ref](https://12factor.net/).

In which situation would a factory override be a benefit?

**Comment by jonathanlukas** [comment]
Configuration via env will only allow the user to connect to a local or a SaaS environment. For self-managed, there might be the requirement to bootstrap a client with a custom configuration. Or do I make wrong assumptions?

**Comment by nikku** [comment]
> Configuration via env will only allow the user to connect to a local or a SaaS environment. For self-managed, there might be the requirement to bootstrap a client with a custom configuration. Or do I make wrong assumptions?

What custom configuration is that exactly? How does self-managed differ from localhost or Saas?

**Comment by jonathanlukas** [comment]
Good point. Looking into it, the that differs is the CredentialsProvider. We offer an interface and the possibility to implement your own. We should keep this.

**Comment by nikku** [comment]
I guess looking it up via `spi` is what you're thinking of?

**Comment by jonathanlukas** [comment]
To stay aligned with the rest, yes. The runtime Main is configured like this (to stay Java SE conform I guess) for the ConnectorFunction as well.
