### ISSUE TITLE
Enable declarative validation configuration for inputs

### ISSUE THREAD

**Issue by jonathanlukas** [camunda/connector-sdk#70]
__Is your feature request related to a problem? Please describe.__

I think it is helpful if a user could validate the connector input in a declarative way (using annotations). These annotations should align with validation mechanisms provided by element templates.

__Describe the solution you'd like__

As a developer, I would like to add annotations to fields of connector input objects which are then automatically validated.

Breakdown:

- [x] Create a new `connector-validation` module/artifact that works as a sidecar (can be added as a dependency if needed).
- [x] Provide an implementation of the [ValidationProvider SPI](https://github.com/camunda/connector-sdk/blob/main/core/src/main/java/io/camunda/connector/api/ValidationProvider.java) (including `META-INF/services` descriptor).
- [x] Use [Java Bean Validation](https://beanvalidation.org/) and [HIbernate Validator](https://hibernate.org/validator/) to allow for declarative, standardized validation usage in Connectors.
- [x] Adjust the SDK README to reflect how to do validation
   - [x] With the new sidecar module using Hibernate Validator
   - [x] With the new sidecar module using another Java Bean Validation implementation (not sure if this is necessary, though)
   - [x] With your own implementation of the ValidationProvider SPI

__Describe alternatives you've considered__

The alternative is programmatic validation which is already in place and quite intuitive to use.

__Additional context__

I was inspired by the [cherry-project](https://github.com/jonathanlukas/zeebe-cherry-framework). This project is dev-first and declares the element template along with the handler function programmatically which causes some coding overhead. I would like to avoid this by using annotations.

**Comment by tmetzke** [comment]
We need to adjust the [SDK documentation](https://docs.camunda.io/docs/next/components/integration-framework/connectors/custom-built-connectors/connector-sdk/) as a follow-up as well.

**Comment by PreetiNirwal** [comment]
Hi @berndruecker - welcome back. 
When you get a moment, if you could provide input on 2 SDK issues that'd be great. 
We're in the process of replacing the imperative-approach to validation & secret replacement with a declarative, annotation-based approach. 
Please see this issue and also issue [here](https://github.com/camunda/connector-sdk/issues/71).
Let us know what you think - thanks!

**Comment by tmetzke** [comment]
@jonathanlukas, I added a little breakdown in the description. Let me know if you have any feedback. 
Would you like to tackle this yourself? If so, can you determine a rough ETA based on your other priorities?
We can also tackle this ourselves or distribute the load, e.g., we prepare the module and you code the provider and tests, or whatever works for you. 🙂

**Comment by jonathanlukas** [comment]
@tmetzke I think I could go for it. Would take 4-8 hours, depending on how easily the hibernate validator is bootstrapped. From the docs, it looks really easy, but you never know...

I would first of all provide you with a very simple implementation. From my perspective, a unit test would not test the behaviour of the validator but of our provider and how it handles validation errors. Then, would add another test to assert the service loader mechanism works as expected to ensure a seamless side-car integration.

Do you agree?

**Comment by tmetzke** [comment]
> I would first of all provide you with a very simple implementation (only using jakarta interfaces). From my perspective, a unit test would not test the behaviour of the validator but of our provider and how it handles validation errors. Then, would add another test to assert the service loader mechanism works as expected to ensure a seamless side-car integration.
> 
> Do you agree?
> 
> I would also mention in the docs that you could exchange the validator implementation by excluding hibernate validator and including the validator of your choice.

That sounds like a good plan (I added more detailed documentation tasks in the breakdown) 👍 
Looking forward! 👀

**Comment by berndruecker** [comment]
If I understand it correctly, we simply allow the passed input object to carry those annotations, and then the connector SDK will automatically validate it? 

That sounds great to me. 

Or is this information also parsed and used for the modeling experience somehow?

**Comment by tmetzke** [comment]
> If I understand it correctly, we simply allow the passed input object to carry those annotations, and then the connector SDK will automatically validate it?
> 
> That sounds great to me.

Exactly 👍 

> Or is this information also parsed and used for the modeling experience somehow?

Currently not, no.
