### ISSUE TITLE
Document how to spin up a Connector during development

### ISSUE THREAD

**Issue by nikku** [camunda/connector-sdk#72]
__Is your feature request related to a problem? Please describe.__

As a connector developer I want to build the connector as quick as possible, in a convenient fashion, and try out that it works in real live.

What keeps me from trying it out in real live is the fact that we don't offer a simple way to _run it_. Spring boot is a great example, as it offers a simple `mvn spring-boot:run` command to start a spring boot app (all strings attached). GCP Functions [offer a similar thing](https://github.com/GoogleCloudPlatform/functions-framework-java#configuration-in-pomxml).

__Describe the solution you'd like__

Provide a simple utility to spin a connector from maven (i.e. `mvn connectors:run`) and register it as a job worker.

This allows me to build the connector iteratively and test it against the real system.

__Describe alternatives you've considered__

* Stick to the existing approach; clearly document how integration testing can be performed (i.e. add job-worker runtime as a test dependency, `mvn exec`, ...
* Provide end-to-end testing facilities (that spin up zeebe, connector, perform integration test, ...)

__Additional context__

This would work nicely with https://github.com/camunda/connector-sdk/issues/12 and validate that the connector is properly configured (to be picked up by our reference run-time) and works as expected.

**Comment by jonathanlukas** [comment]
For the testing stuff:

This sounds to me like you could utilize [zeebe-process-test](https://github.com/camunda/zeebe-process-test) here and enhance it for the testing.

Idea:

A Junit extension that allows scenario tests with the connector.

Requirements: 
* The element template should be present to generate a process.
* The connector function should be registered via SPI to be discoverable.
* The process definition should have configurable properties that define the actual implementation of the element template for a given scenario.
* The connector function is registered as worker with the job type defined in the element template (either configured manually or discovered in some way).
* The process instance takes input variables at start and returns output variables on complete.

Pseudo test code:

```java

// assuming there is only one element template for the connector
@ConnectorFunctionTest("path/to/elementTemplate.json")
public class MyConnectorFunctionTest {
  ConnectorSimulator connectorSimulator;

  @Test
  public void shouldReturnSomething() {
    // given
    Map<String,String> properties = mockProperties();
    InputType connectorInput = mockInput();
    // when
    OutputType connectorOutput = connectorSimulator.simulate(properties, connectorInput);
    // then
    assertThat(connectorOutput)...
    }
}
```

@nikku wdyt?

For the maven plugin: Maybe it would be easier to just provide a simple runtime inside an existing framework like quarkus or spring-boot and use existing functionality.
Downside: This could lead implementors to use this runtime also for production...

**Comment by nikku** [comment]
> For the maven plugin

The goal is literally to be able to spin the thing up in the simples possible way. From experience I know that people love to test the real thing, no matter how great our connector testing story is.

**Comment by nikku** [comment]
Of course practical advice how to test end-to-end (using zeebe-process-test or ezy) is great, too.

**Comment by jonathanlukas** [comment]
I see your point. Touching running things gives the developer a better feeling on how the connector will behave like in production.

But is writing another maven plugin the way? Maybe we could hook into quarkus. They have extensive maven tooling like a runner + they have a google cloud function extension (in preview): https://quarkus.io/guides/gcp-functions

**Comment by nikku** [comment]
> But is writing another maven plugin the way?

Why not if there exists `spring-boot:run`?

**Comment by jonathanlukas** [comment]
I would say there will be development and maintenance work for a maven plugin. And there are already other things out there.

Also, implementers would have to apply something new.

**Comment by nikku** [comment]
Moving to backlog. Not an immediate priority for us.

**Comment by berndruecker** [comment]
I think one good way to go about this is to start a simple Spring Boot app from within the `test` scope of the connector project.

This is how I did it in a super early prototype: https://github.com/camunda/connector-sdk/blob/bernd-inbound/example-amqp/src/test/java/org/camunda/community/connector/amqp/RunAsWorkerApplication.java

So I think it is already possible, especially as spring-zeebe can now run OutboundConnectors directly, we need to 

* add an example
* add docs

I think this important for Connector developers, so I might give it a first stab soon

**Comment by igpetrov** [comment]
I think, this was implemented in 0.3.0.
Currently, once a developer built a connector, they can launch it with current 0.3.0 SDK as follows:
- Build SDK `mvn clean package install`
- Build own connector with the SDK
- Run `java -cp '<path-to-runtime>.jar:<path-to-connector>.jar' -Dserver.port=9898 -Dzeebe.client.broker.gateway-address=127.0.0.1:26500 -Dzeebe.client.security.plaintext=true io.camunda.connector.runtime.ConnectorRuntimeApplication` or relevant configs, such as port, and/or Zeebe broker address.

Does it sound easy or do you think it can be simplified? @nikku @berndruecker

**Comment by nikku** [comment]
I personally think that is still three lines to many (consider `mvn function:run` or `mvn spring-boot:run` as the designated alternatives.

**Comment by berndruecker** [comment]
Added a test dependency allows to start the connector from within your IDE and also debug into things - so from a developers perspective, I would see this as the default way of doing things. 

Using bash would be more kind of an integration test way of probably doing a double check before release. 

I am happy to add another paragraph to https://docs.camunda.io/docs/components/connectors/custom-built-connectors/connector-sdk/#runtime-environments but would wait for the 0.3.0 to be released and create a separate PR for this one.

Then I think we can close this issue.

**Comment by berndruecker** [comment]
Will be fixed with https://github.com/camunda/connector-sdk/issues/271, so closing this one
