### ISSUE TITLE
Rework `ConnectorJobHandler` tests

### ISSUE THREAD

**Issue by igpetrov** [camunda/connector-sdk#73]
__What should we do?__

Rework `ConnectorJobHandler` tests in order to verify that the right exceptions are thrown in [the related code block](https://github.com/camunda/connector-sdk/blob/32982715dd9f877b357e5ef1b4d0f5d0b93b5862/runtime-util/src/main/java/io/camunda/connector/runtime/util/outbound/ConnectorJobHandler.java#L88-L89).

__Why should we do it?__

In scope of the PR https://github.com/camunda/connector-sdk/pull/66 we discovered some some test cases (exception handling) is very hard to test. Having strong and robust testing is a strong requirement for SDK-tier libraries.

**Comment by MaxTru** [comment]
@igpetrov could you please correct the link? Currently it is broken. Thanks

> Rework ConnectorJobHandler tests in order to verify that the right exceptions are thrown in [the related code block](https://github.com/camunda/connector-sdk/blob/main/runtime-job-worker/src/main/java/io/camunda/connector/runtime/jobworker/ConnectorJobHandler.java#L67-L71).

**Comment by igpetrov** [comment]
Updated

**Comment by igpetrov** [comment]
Became irrelevant with 0.3.0 release.
