### ISSUE TITLE
Be able to handle (larger) data with connectors

### ISSUE THREAD

**Issue by nikku** [camunda/connector-sdk#77]
__Is your feature request related to a problem? Please describe.__

As a user I'm following Camunda best practices to [only store relevant data](https://docs.camunda.io/docs/next/components/best-practices/development/handling-data-in-processes/#storing-just-the-relevant-data). All bigger chunks of (binary) data (PDF, images) used in my processes are stored on a dedicated storage service ([Google Drive](https://www.google.com/drive/) for example) and only references to that data are stored in the process.

Now I want to create a connector to integrate an OCR system. That system requires input of PDF and/or image binary and returns back the recognized text.

How do I create such connector in a way that it is storage layer agnostic?

__Describe the solution you'd like__

* Be able to read (binary) data from external systems before consuming it in a connector
* Be able to write (binary) data to an external system that is the result of the connector invocation
* Prevent external data to be written as an engine variable

__Describe alternatives you've considered__

None.

__Additional context__

None.

**Comment by sbuettner** [comment]
When running in a cloud based environment I would recommend to leverage external storage like AWS S3 and just pass the reference to an object around. The connector would download, process and possibly update/create a new object using external storage mechanisms.
