### ISSUE TITLE
Secret replacement with maps does currently not work in the SDK

### ISSUE THREAD

**Issue by akulminskyi** [camunda/connector-sdk#78]
__What should we do?__

Update SDK to support Secret replacement with Maps using @Secret annotation

__Why should we do it?__

Secret replacement with Maps does currently not work in the SDK.

Description:

https://github.com/camunda/team-connectors/issues/67
https://github.com/camunda/connector-sdk/issues/71

**Comment by tmetzke** [comment]
Thanks @akulminskyi, I am already working on this. 👍
