### ISSUE TITLE
Implement output mapping in Job Worker run-time

### ISSUE THREAD

**Issue by nikku** [camunda/connector-sdk#8]
__Describe the problem__

We should implement all output mapping features supported by connectors:

![image](https://user-images.githubusercontent.com/58601/184882701-a2befe11-8094-401b-be99-33ea675b2716.png)

Right now output mappings are not sufficently supported by the job worker run-time.

__Describe the solution__

* [x] Support `resultVariable` mapping (https://github.com/camunda/connector-sdk/pull/59)
* [ ] Support dynamic mapping
    * Extract using FEEL
    * Fail if output mapping fails and raise incident
    * Related https://github.com/camunda/connector-sdk/pull/66

**Comment by nikku** [comment]
Moving this one to ready for folks to pick-up. 

Without full support of output mappings connectors are of limited use for users.

**Comment by igpetrov** [comment]
Hi @tmetzke,

As I am picking this task with minimal context, just wanted to double-check. Is the goal of this task to introduce support for the `Result Expression` as it is implemented in [`ConnectorOutputVariablesFactory`](https://github.com/camunda/cloud-connector-bridge/blob/main/src/main/java/io/camunda/connectorbridge/invoker/ConnectorOutputVariablesFactory.java)?
