### ISSUE TITLE
Allow to ignore incompatible types in secret replacement 

### ISSUE THREAD

**Issue by tmetzke** [camunda/connector-sdk#82]
__Is your feature request related to a problem? Please describe.__

I want to replace secrets in a Java Map of arbitrary objects that I got from a JSON object. It can contain numbers and booleans besides Strings that contain secrets.

__Describe the solution you'd like__

I would like to define if incompatible types in secret replacement should be silently ignored.

I would like to either define this in general when calling `context.replaceSecrets` or in the `@Secret` annotation of the Map.

__Describe alternatives you've considered__

* I can get the secret store from the context and do secret replacement manually for the Map. I would like to reuse the existing replacement capabilities though.

__Additional context__

n/a

**Comment by nikku** [comment]
To better understand your requirement:

* You'd like to annotate a map `@Secret`
* So that primitive values in it matching the pattern `secret.SOME_SECRET` are being replaced?


```java
record Foo(@Secret Map<String, Object> keys)
```

**Comment by tmetzke** [comment]
Exactly, yeah. Currently, we are throwing an exception if a value is neither a String nor a container type (i.e. a Java primitive, Boolean, or Number). We could also think about making this the default behavior for anonymous container types like Lists, Maps, and Sets.

**Comment by nikku** [comment]
I do think the bigger (and related!) issue is replacing secrets within a string:

```
= {
  Authorization: "bearer {{ secrets.MY_BEARER_TOKEN }}"
}
```

**Comment by tmetzke** [comment]
I agree that that one is bigger. I don't see how they are related, though.

**Comment by nikku** [comment]
Related in a sense that both target maps, and [the former](https://github.com/camunda/connector-sdk/issues/82#issuecomment-1250639481) has been reported by a user :wink

**Comment by tmetzke** [comment]
OK, yes, absolutely. That is something we can take into account upon prioritizing this (and the other issue). I think we won't get the other issue into SDK `0.2.0`.

**Comment by tmetzke** [comment]
Superseded by #264
