### ISSUE TITLE
Be able to monitor / debug the job worker connector run-time

### ISSUE THREAD

**Issue by nikku** [camunda/connector-sdk#97]
__Is your feature request related to a problem? Please describe.__

As a user in an IT landscape I want to understand if / when my application components are running. The basic way to do this is through health checks (identify if my component is healthy), metrics (details on state, i.e. error rate or response times) and the log stream (output).

I want to be able to monitor my running job workers in this way.

__Describe the solution you'd like__

* Offer built-in hooks to health checks / export metrics with the stock connector run-time 

__Describe alternatives you've considered__

* Customers build the connector run-time themselves ([ref](https://camunda.slack.com/archives/C02JLRNQQ05/p1663655708081599?thread_ts=1663648629.207079&cid=C02JLRNQQ05)).

__Additional context__

Came up in a couple of discussions, including [this one](https://camunda.slack.com/archives/C02JLRNQQ05/p1663648629207079).

**Comment by berndruecker** [comment]
I think this should be not solved within the connectors project now - but on a Zeebe/Operate level first, as this is foremost also a problem for any job worker - WDYT @felix-mueller ?

I agree that there is some inbound specific story to it, but I would postpone this until we know what we do on Zeebe Job Worker level. So closing this for now (feel free to object)
